development: &default
  massage_duration: <%= 15.minutes %>
  massage_start: '9:00'
  massage_end: '18:00'
  time_to_open_schedule: '07:00'
  location: Sala Quick Massage
  pauses: [['10:30', '10:45'], ['12:00', '13:00'], ['16:30', '16:45']]
  massage_day_given_a_day_with_schedule:
    Friday: Monday
    Saturday: Monday
    Sunday: Monday
    Monday: Monday
    Tuesday: Wednesday
    Wednesday: Wednesday
    Thursday: Friday

test:
  <<: *default

production:
  <<: *default
